{{- if and .Values.agentService.enabled .Values.agentService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "voice-agent.fullname" . }}-agent
  labels:
    {{- include "voice-agent.agent.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "voice-agent.fullname" . }}-agent
  minReplicas: {{ .Values.agentService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.agentService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.agentService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.agentService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.agentService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.agentService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
      selectPolicy: Max
{{- end }}
